variable "env" {}
variable "vpc_cidr_block" {}
variable "web_subnet_cidr_block" {}
variable "app_subnet_cidr_block" {}
variable "db_subnet_cidr_block" {}
variable "az" {}
variable "tags" {}
variable "default_vpc_id" {}
variable "default_vpc_rt" {}
variable "default_vpc_cidr_block" {}